import ast
from pathlib import Path

from .classifier import classify_module
from .ignore_rules import IgnoreRule, filter_findings
from .models import Finding


_EXCLUDED_DIRS = {"test", "tests", "__tests__", "generated", "autogenerated"}


def check_common_usage(
    paths: list[Path],
    root: Path,
    classification_root: Path | None,
    common_roots: tuple[str, ...],
    ignore_rules: tuple[IgnoreRule, ...],
) -> list[Finding]:
    candidates = {
        path: _module_name(path, root)
        for path in paths
        if classify_module(path, classification_root, common_roots).layer == "common"
        and not _excluded(path, root)
        and not _generated(path)
    }
    references: dict[Path, set[str]] = {path: set() for path in candidates}
    module_paths: dict[str, Path] = {name: path for path, name in candidates.items() if name}

    for source_path in paths:
        if _excluded(source_path, root) or _generated(source_path):
            continue
        source_layer = classify_module(
            source_path, classification_root, common_roots
        ).layer
        if source_layer not in {"ui", "process", "data"}:
            continue
        try:
            tree = ast.parse(source_path.read_text(encoding="utf-8"), filename=str(source_path))
        except (OSError, UnicodeError, SyntaxError):
            continue
        for imported in _imports(tree, source_path, root):
            for module_name, asset_path in module_paths.items():
                if _matches_import(imported, module_name):
                    references[asset_path].add(source_layer)

    findings: list[Finding] = []
    for asset_path, layers in references.items():
        if len(layers) != 1:
            continue
        relative = _relative_text(asset_path, root)
        finding = Finding(
            Path(relative),
            1,
            "UPD407",
            "Common/Shared asset is referenced by only one layer; consider moving it into that layer",
            "warning",
        )
        try:
            source = asset_path.read_text(encoding="utf-8")
        except (OSError, UnicodeError):
            source = ""
        findings.extend(filter_findings([finding], source, relative, ignore_rules))
    return findings


def _module_name(path: Path, root: Path) -> str:
    try:
        relative = path.relative_to(root)
    except ValueError:
        relative = path
    parts = list(relative.with_suffix("").parts)
    if parts and parts[-1] == "__init__":
        parts.pop()
    return ".".join(parts)


def _imports(tree: ast.AST, source_path: Path, root: Path) -> set[str]:
    result: set[str] = set()
    for node in ast.walk(tree):
        if isinstance(node, ast.Import):
            result.update(alias.name for alias in node.names)
        elif isinstance(node, ast.ImportFrom):
            base = _import_base(node, source_path, root)
            if base:
                result.add(base)
            result.update(f"{base}.{alias.name}" if base else alias.name for alias in node.names)
    return result


def _import_base(node: ast.ImportFrom, source_path: Path, root: Path) -> str:
    if node.level == 0:
        return node.module or ""
    try:
        package_path = source_path.parent.relative_to(root)
    except ValueError:
        package_path = source_path.parent
    parts = list(package_path.parts)
    parent_count = max(0, node.level - 1)
    if parent_count:
        parts = parts[:-parent_count] if parent_count < len(parts) else []
    if node.module:
        parts.extend(node.module.split("."))
    return ".".join(parts)


def _matches_import(imported: str, module_name: str) -> bool:
    return (
        imported == module_name
        or imported.startswith(module_name + ".")
    )


def _excluded(path: Path, root: Path) -> bool:
    try:
        parts = path.relative_to(root).parts
    except ValueError:
        parts = path.parts
    return any(part.lower() in _EXCLUDED_DIRS for part in parts[:-1])


def _generated(path: Path) -> bool:
    try:
        lines = path.read_text(encoding="utf-8").splitlines()[:5]
    except (OSError, UnicodeError):
        return False
    return any(
        marker in line.lower()
        for line in lines
        for marker in ("generated by", "auto-generated", "autogenerated")
    )


def _relative_text(path: Path, root: Path) -> str:
    try:
        return path.relative_to(root).as_posix()
    except ValueError:
        return path.as_posix()
