using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace UpdCommanderChecker;

internal static class CommonUsageRules
{
    private static readonly HashSet<string> ExcludedDirectories =
        ["test", "tests", "__tests__", "generated", "autogenerated"];

    internal static IReadOnlyList<Finding> Check(
        IReadOnlyList<ParsedSource> sources,
        SemanticProject project,
        IReadOnlyList<string> commonRoots,
        IReadOnlyList<IgnoreRule> ignoreRules
    )
    {
        var candidates = sources
            .Where(source =>
                Classifier.ClassifyPath(source.Relative, commonRoots).Layer == "common"
                && !Excluded(source.Relative)
                && !Generated(source)
            )
            .ToDictionary(source => source.Relative, _ => new HashSet<string>(), StringComparer.OrdinalIgnoreCase);
        foreach (var source in sources.Where(source => !Excluded(source.Relative) && !Generated(source)))
        {
            var layer = Classifier.ClassifyPath(source.Relative, commonRoots).Layer;
            if (layer is not ("ui" or "process" or "data"))
            {
                continue;
            }

            var model = project.GetModel(source.Tree);
            foreach (var node in source.Root.DescendantNodes().Where(IsReferenceNode))
            {
                if (node.AncestorsAndSelf().Any(ancestor => ancestor is UsingDirectiveSyntax))
                {
                    continue;
                }
                ISymbol? symbol = node is IdentifierNameSyntax identifier
                    ? model.GetAliasInfo(identifier)?.Target
                    : null;
                symbol ??= model.GetSymbolInfo(node).Symbol;
                if (symbol is null)
                {
                    continue;
                }
                foreach (var targetPath in project.FindSourcePaths(symbol))
                {
                    if (candidates.TryGetValue(targetPath, out var layers))
                    {
                        layers.Add(layer);
                    }
                }
            }
        }

        var findings = new List<Finding>();
        foreach (var source in sources)
        {
            if (!candidates.TryGetValue(source.Relative, out var layers) || layers.Count != 1)
            {
                continue;
            }
            var lineText = source.Lines.FirstOrDefault() ?? string.Empty;
            if (IgnoreRules.IsIgnored(new IgnoreCheckInput(source.Relative, "UPD407", lineText, ignoreRules)))
            {
                continue;
            }
            findings.Add(new Finding(
                source.Relative,
                1,
                "UPD407",
                "Common/Shared asset is referenced by only one layer; consider moving it into that layer",
                "warning"
            ));
        }
        return findings;
    }

    private static bool IsReferenceNode(SyntaxNode node)
    {
        return node is IdentifierNameSyntax or GenericNameSyntax;
    }

    private static bool Excluded(string relative)
    {
        var parts = relative.Replace('\\', '/').Split('/');
        return parts.Take(parts.Length - 1).Any(part => ExcludedDirectories.Contains(part.ToLowerInvariant()));
    }

    private static bool Generated(ParsedSource source)
    {
        return source.Relative.EndsWith(".g.cs", StringComparison.OrdinalIgnoreCase)
            || source.Relative.EndsWith(".generated.cs", StringComparison.OrdinalIgnoreCase)
            || source.Lines.Take(5).Any(line => line.Contains("<auto-generated", StringComparison.OrdinalIgnoreCase));
    }
}
