package checker

import (
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"strings"
)

func checkCommonUsage(paths []string, root string, commonRoots []string, rules []IgnoreRule) []Finding {
	assets := map[string][]string{}
	for _, path := range paths {
		relative, err := filepath.Rel(root, path)
		if err != nil || excludedCommonUsagePath(relative) || strings.HasSuffix(strings.ToLower(path), "_test.go") || generatedGoFile(path) {
			continue
		}
		if ClassifyPathWithCommonRoots(filepath.ToSlash(relative), commonRoots).Layer == "common" {
			directory := filepath.ToSlash(filepath.Dir(relative))
			assets[directory] = append(assets[directory], path)
		}
	}
	if len(assets) == 0 {
		return nil
	}

	refs := map[string]map[string]bool{}
	for _, path := range paths {
		relative, err := filepath.Rel(root, path)
		if err != nil || excludedCommonUsagePath(relative) || strings.HasSuffix(strings.ToLower(path), "_test.go") || generatedGoFile(path) {
			continue
		}
		sourceLayer := ClassifyPathWithCommonRoots(filepath.ToSlash(relative), commonRoots).Layer
		if sourceLayer != "ui" && sourceLayer != "process" && sourceLayer != "data" {
			continue
		}
		file, parseErr := parser.ParseFile(token.NewFileSet(), path, nil, parser.ImportsOnly)
		if parseErr != nil || file == nil {
			continue
		}
		for _, spec := range file.Imports {
			importPath := strings.Trim(spec.Path.Value, "\"")
			for assetDirectory := range assets {
				if importPath == assetDirectory || strings.HasSuffix(importPath, "/"+assetDirectory) {
					if refs[assetDirectory] == nil {
						refs[assetDirectory] = map[string]bool{}
					}
					refs[assetDirectory][sourceLayer] = true
				}
			}
		}
	}

	var findings []Finding
	for assetDirectory, assetPaths := range assets {
		if len(refs[assetDirectory]) != 1 {
			continue
		}
		for _, assetPath := range assetPaths {
			relative, err := filepath.Rel(root, assetPath)
			if err != nil {
				continue
			}
			lines := readLines(assetPath)
			addFinding(&findings, filepath.ToSlash(relative), 1, "UPD407", "Common/Shared asset is referenced by only one layer; consider moving it into that layer", "warning", lines, rules)
		}
	}
	return findings
}

func excludedCommonUsagePath(path string) bool {
	for _, part := range strings.Split(strings.ToLower(filepath.ToSlash(path)), "/") {
		switch part {
		case "test", "tests", "__tests__", "generated", "autogenerated":
			return true
		}
	}
	return false
}

func generatedGoFile(path string) bool {
	data, err := os.ReadFile(path)
	return err == nil && strings.Contains(string(data), "Code generated")
}
