package checker

import (
	"os"
	"path/filepath"
	"testing"
)

func TestCommonUsageWarningLayerCountsAndExclusions(t *testing.T) {
	for _, test := range []struct {
		name   string
		layers []string
		want   bool
	}{
		{name: "one layer", layers: []string{"ui"}, want: true},
		{name: "two layers", layers: []string{"ui", "process"}},
		{name: "three layers", layers: []string{"ui", "process", "data"}},
		{name: "unused"},
	} {
		t.Run(test.name, func(t *testing.T) {
			root := t.TempDir()
			writeTestFile(t, filepath.Join(root, "common", "contracts", "message.go"), "package contracts\ntype Message struct{}\n")
			for _, layer := range test.layers {
				path := filepath.Join(root, layer, "consumer.go")
				writeTestFile(t, path, "package consumer\nimport _ \"example/common/contracts\"\n")
			}
			findings := ScanPath(root, nil)
			if test.want {
				assertHasCode(codeAssertionInput{t: t, findings: findings, code: "UPD407"})
			} else {
				assertNoCode(codeAssertionInput{t: t, findings: findings, code: "UPD407"})
			}
		})
	}
}

func TestCommonUsageIgnoresTestGeneratedAndRuleExcludedReferences(t *testing.T) {
	for _, relative := range []string{
		"ui/tests/consumer_test.go",
		"ui/generated/consumer.go",
	} {
		t.Run(relative, func(t *testing.T) {
			root := t.TempDir()
			writeTestFile(t, filepath.Join(root, "common", "contracts", "message.go"), "package contracts\ntype Message struct{}\n")
			content := "package consumer\nimport _ \"example/common/contracts\"\n"
			if filepath.Base(relative) == "consumer.go" {
				content = "// Code generated by fixture. DO NOT EDIT.\n" + content
			}
			writeTestFile(t, filepath.Join(root, filepath.FromSlash(relative)), content)
			assertNoCode(codeAssertionInput{t: t, findings: ScanPath(root, nil), code: "UPD407"})
		})
	}

	root := t.TempDir()
	writeTestFile(t, filepath.Join(root, "contracts", "message.go"), "package contracts\ntype Message struct{}\n")
	writeTestFile(t, filepath.Join(root, "ui", "consumer.go"), "package consumer\nimport _ \"example/contracts\"\n")
	findings := ScanPathWithCommonRoots(root, nil, 2, 12, 80, 3, 2, []string{"contracts"})
	assertHasCode(codeAssertionInput{t: t, findings: findings, code: "UPD407"})
	if err := os.WriteFile(filepath.Join(root, ".updcommanderignore"), []byte("UPD407 contracts/**\n"), 0o644); err != nil {
		t.Fatal(err)
	}
	findings = ScanPathWithCommonRoots(root, nil, 2, 12, 80, 3, 2, []string{"contracts"})
	assertNoCode(codeAssertionInput{t: t, findings: findings, code: "UPD407"})
}
