import tempfile
import unittest
from pathlib import Path

from upd_commander_checker.scanner import scan_path


class CommonUsageRuleTests(unittest.TestCase):
    def _project(self, root: Path, layers: tuple[str, ...]) -> None:
        common = root / "common" / "contracts" / "message.py"
        common.parent.mkdir(parents=True, exist_ok=True)
        common.write_text("class Message: pass\n", encoding="utf-8")
        for layer in layers:
            consumer = root / layer / "consumer.py"
            consumer.parent.mkdir(parents=True, exist_ok=True)
            consumer.write_text(
                "from common.contracts.message import Message\n"
                "value = Message()\n",
                encoding="utf-8",
            )

    def test_one_referring_layer_emits_warning(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._project(root, ("ui",))

            findings = [item for item in scan_path(root) if item.code == "UPD407"]

            self.assertEqual(1, len(findings))
            self.assertEqual("warning", findings[0].severity)
            self.assertEqual(Path("common/contracts/message.py"), findings[0].path)

    def test_two_and_three_layers_do_not_emit_warning(self) -> None:
        for layers in (("ui", "process"), ("ui", "process", "data")):
            with self.subTest(layers=layers), tempfile.TemporaryDirectory() as directory:
                root = Path(directory)
                self._project(root, layers)
                self.assertFalse(any(item.code == "UPD407" for item in scan_path(root)))

    def test_unused_and_public_declaration_only_assets_are_not_reported(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            self._project(root, ())

            self.assertFalse(any(item.code == "UPD407" for item in scan_path(root)))

    def test_test_and_generated_references_do_not_count(self) -> None:
        for relative, content in (
            ("ui/tests/test_consumer.py", "from common.contracts.message import Message\n"),
            (
                "ui/generated_consumer.py",
                "# Generated by fixture\nfrom common.contracts.message import Message\n",
            ),
        ):
            with self.subTest(relative=relative), tempfile.TemporaryDirectory() as directory:
                root = Path(directory)
                self._project(root, ())
                path = root / relative
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content, encoding="utf-8")
                self.assertFalse(any(item.code == "UPD407" for item in scan_path(root)))

    def test_rule_ignore_and_custom_common_root(self) -> None:
        with tempfile.TemporaryDirectory() as directory:
            root = Path(directory)
            asset = root / "contracts" / "message.py"
            asset.parent.mkdir(parents=True)
            asset.write_text("class Message: pass\n", encoding="utf-8")
            consumer = root / "ui" / "consumer.py"
            consumer.parent.mkdir(parents=True)
            consumer.write_text("from contracts.message import Message\nMessage()\n", encoding="utf-8")
            self.assertTrue(any(item.code == "UPD407" for item in scan_path(root, common_roots=("contracts",))))

            (root / ".updcommanderignore").write_text(
                "UPD407 contracts/**\n", encoding="utf-8"
            )
            self.assertFalse(
                any(
                    item.code == "UPD407"
                    for item in scan_path(root, common_roots=("contracts",))
                )
            )


if __name__ == "__main__":
    unittest.main()
